name: Build dev

on:
  push:
    branches: [ci]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git checkout dev
          sudo chmod +x vault.sh
          /cybergame-dev/data/frontend/.env?version=9
          ./vault.sh ${{ secrets.VAULT_URL }}/cybergame-dev/data/frontend/.env env ${{ secrets.VAULT_TOKEN }}
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t cyberrich/web-practice-dev:dev .
          docker push cyberrich/web-practice-dev:dev

  deploy:
    needs: [ build ]
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Write kube config
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" >> kube_config.yaml
      - name: Deploy to kubernetes
        run: |
          cd manifest/dev
          kubectl --kubeconfig=../../kube_config.yaml apply -f dev-deployment.yaml
          kubectl --kubeconfig=../../kube_config.yaml rollout restart -f dev-deployment.yaml -n practice-web
          kubectl --kubeconfig=../../kube_config.yaml apply -f dev-service.yaml
          kubectl --kubeconfig=../../kube_config.yaml apply -f dev-ingress.yaml