---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-web-dev
  namespace: dunk-practice-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice-web-dev
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: practice-web-dev
    spec:
      imagePullSecrets:
        - name: practice-web-registrykey
      containers:
        - name: practice-web-dev
          image: cyberrich/web-practice-dev:dev
          imagePullPolicy: Always
          #          livenessProbe:
          #            httpGet:
          #              path: /actuator/health/liveness
          #              port: 3000
          #            initialDelaySeconds: 15
          #            periodSeconds: 4
          #          readinessProbe:
          #            httpGet:
          #              path: /actuator/health/readiness
          #              port: 3000
          #            initialDelaySeconds: 15
          #            periodSeconds: 4
          ports:
            - name: http
              containerPort: 3000