apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-practice-web-dev
  namespace: dunk-practice-dev
spec:
  rules:
    - host: dunk-web-dev.cbgame88.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: practice-web-dev
                port:
                  number: 3000

  ingressClassName: nginx